sudo: false

language: node_js
node_js: node
script:
  - yarn lint
branches:
  only:
  - master
  - "/v\\d\\./"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  - provider: heroku
    app: staging-zp-wallet
    api_key: $HEROKU_API_KEY
  - provider: heroku
    app: zp-wallet
    api_key: $HEROKU_API_KEY
    on:
      tags: true
      all_branches: true
